name: Test

on:
  push:
    branches: ["master"]
  merge_group:
  pull_request:
    branches: ["master"]

jobs:
  test:

    name: Test PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        id: composer-cache-restore
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: (test -d vendor && echo vendor directory exists) || composer install --prefer-dist --no-progress --no-suggest

      - name: Run psalm
        run: ./vendor/bin/psalm

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml --json_path=/tmp/coverage.json -v